version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install pytest==6.2.5
  build:
    commands:
      - python -m pytest -v
cache:
  paths:
    - '/root/.cache/**/*'